### ISSUE TITLE
Implement passing channel options in useChannel

### ISSUE THREAD

**Issue by AndyNicks** [ably-labs/react-hooks#12]
A customer tryed to implement encryption using these hooks: https://ably.com/docs/realtime/encryption

useChannel function doesn't support passing channel options:
https://github.com/ably-labs/react-hooks/blob/main/src/hooks/useChannel.ts#L11-L14

so we'd need to add that as an argument and pass it to channels.get

**Comment by thisisjofrank** [comment]
I've updated the package to now support passing channel options.

**Comment by herzog0** [comment]
I'm getting an error when trying to pass channel options in the useChannel hook: 
![image](https://user-images.githubusercontent.com/35974312/195573288-7898dd86-63ab-4d01-b0fa-f7342f8cae53.png)

Any ideas?

My package version is: 
"@ably-labs/react-hooks": "^2.0.9",

```
  const [channel] = useChannel(
    {
      channelName: room,
      options: {
        params: { rewind: "20" }, // https://ably.com/docs/realtime/channels/channel-parameters/rewind
      },
    },
  }
```

**Comment by ronastlelobo** [comment]
@herzog0 any luck finding the solution? I am also stuck with this.
