### ISSUE TITLE
FEATURE: A way to force refresh the token, or clear the existing instance / client

### ISSUE THREAD

**Issue by cor1** [ably-labs/react-hooks#25]
Hello, So far I have not found a way to force refresh an authentication token to update user claims or clear the instance. The use cases are the following:

The user token is scoped to "workspaces" if the user creates a new workspace or is a new user, the claims need to be updated. There does not currently appear to be a way to do this.

If the user logs out, the token / client ID should be able to be cleared so that if a new user logs in they don't get the same ably instance as the previous user. Currently, a hard refresh of the page is required.

Please let me know if there is a better or existing way to achieve this.

**Comment by cor1** [comment]
It appears a workaround is to revoke the token which will cause the front end SDK to refetch a token.

**Comment by cor1** [comment]
Update: looks like this can be worked around by revoking tokens.

**Comment by owenpearson** [comment]
Hey @cor1, sorry for the delayed response! The standard way to update capabilities on an existing Ably connection is to use the `client.auth.authorize` method. Calling this will request a new token using the `authUrl` or `authCallback` provided in your ClientOptions which will give you a chance to send a new token/TokenRequest/JWT from your auth server with an updated capability set. Hope this helps, let me know if you have any further qs

**Comment by cor1** [comment]
@owenpearson that worked great. Thanks!
