### ISSUE TITLE
Get which client is you in `usePresence`

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ably-labs/react-hooks#31]
Right now there is only this information for each client:
![screenshot](https://user-images.githubusercontent.com/52586855/218352785-b6db7b45-c6bf-4191-bee7-57fb2e7cb206.png)
but how do I find out which one is "me"?

**Comment by owenpearson** [comment]
Hey @ChocolateLoverRaj, thank you for reaching out and sorry for the late response! The best way to do this currently is to test against the `PresenceMessage.clientId` field. If you already know the clientId then it should be as simple as `presenceData.find(x => x.clientId === myClientId)`. If you're using token authentication and the clientId is not known until after the token has been received then the best way to do this would be to pass in your own ably client:

```ts
import { useChannel, Realtime } from '@ably-labs/react-hooks'

const realtime = new Realtime(options);

const [presenceData] = usePresence({ channelName: "your-channel-name", realtime: realtime })

const myPresenceData = presenceData.find(x => x.clientId === realtime.auth.clientId);
```

Let me know if you have any further questions
