### ISSUE TITLE
Get the current message in `usePresence`

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [ably-labs/react-hooks#32]
I'm using `usePresence` like this:

```tsx
const [presenceData, updateStatus] = usePresence('connect', 'A person name')
```

I want to have an input to change the message. Something like this:

```tsx
<input
  value={status}
  onChange={() => {
    // update status
  }}
/>
```

I could use a `useState` for status, but I think that would result in duplicate data and could lead to inconsistencies.

**Comment by owenpearson** [comment]
closing this as stale for now
