### ISSUE TITLE
SyntaxError: Unexpected token 'export' with Next.js

### ISSUE THREAD

**Issue by mariesta** [ably-labs/react-hooks#7]
# Context
`ably-labs/react-hooks` exports as a ES6 module. Unfortunately, Next.js doesn't transpile functions imported from node_modules. As a result, importing `ably-labs/react-hooks` causes an issue (SyntaxError: Unexpected token 'export' with Next.js)

# Possible Fix
Update the documentation and explain that for Next.js, developers need to install [next-transpile-modules](https://github.com/martpie/next-transpile-modules#readme) and update `next.config.js` with:
```
const withTM = require('next-transpile-modules')(['@ably-labs/react-hooks']);

module.exports = withTM({...})
```

**Comment by itwilson** [comment]
This solution works for me. Thanks!

**Comment by thisisjofrank** [comment]
Thanks for this feedback, we have updated the readme to include this helpful advice.
